### ISSUE TITLE
Support CREATE and `PROJECTION` operations

### ISSUE THREAD

**Issue by pimotte** [discipl/discipl-law-reg#113]
A CREATE operation takes one operand, an expression which details the "contents" of the fact. We can use AND/OR for this (interprete as composite data type/enum respectively). At some point, we also want to support using LISTs in a CREATE operation. 

The current `<<>>` syntax can be replaced by a CREATE operation with as operand a boolean LITERAL true.

PROJECTION is a temporary name, I'm open to other names.

A PROJECTION operation takes two operands: A fact that is defined by a CREATE expression, and a fact that is contained in that CREATE expression.

The value of a PROJECTION operation is the specific value of the fact in the context where the created fact was instantiated.

**Comment by blackstardlb** [comment]
Implemented in #117
