### ISSUE TITLE
Boolean logic for facts

### ISSUE THREAD

**Issue by pimotte** [discipl/discipl-law-reg#5]
Parse and evaluate the boolean logic in facts (EN OF NIET)

**Comment by bkaptijn** [comment]
underway introducing parser based on pegjs... but there are other choices that can be made: for instance look at: https://tomassetti.me/parsing-in-javascript/#parserGenerators 

any advice @pimotte ?

**Comment by pimotte** [comment]
I have no particular experience with parsing in javascript, but pegjs looks good to me.
